# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04d995f694afce81e40d9bb162e7ffe5d60a96f62d01f5f74d0698ac00dbe0dbae2a9a69dcdc822c2fcb5317bae799cea96aaa86ca6640f8fe156c0a23807e83

test:
  secret_key_base: 076fa96887fde16bc2559216f4874d26928dcc9573693adb01344e6dca41a5134036470a80c8143ac75c7b668f494bc478912008f543b4a27a927bb5a6b41e67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
